version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "*/1 * * * *"

  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: "daily"
