name: Cargo Benches

on:
    push:
        branches: [ "*" ]
    pull_request:
        branches: [ "*" ]

jobs:
    cargo_benches:
        name: Run cargo benches
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Cache cargo registry and target
              uses: actions/cache@v4
              with:
                path: |
                  ~/.cargo/registry
                  ~/.cargo/git
                  target
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Setup Rust toolchain
              uses: moonrepo/setup-rust@v0
              with:
                channel: stable
                bins: cargo-codspeed

            - name: Run the benchmarks
              run: cargo bench --all
